"""Initial migration

Revision ID: 2f7022079b6d
Revises: b654faf5af09
Create Date: 2024-07-16 13:44:11.070843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7022079b6d'
down_revision = 'b654faf5af09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_pizzas', 'price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('restaurant_pizzas', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('restaurant_pizzas', 'pizza_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_pizzas', 'pizza_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('restaurant_pizzas', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('restaurant_pizzas', 'price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
