"""message

Revision ID: b654faf5af09
Revises: eae6992b4b7c
Create Date: 2024-07-02 14:11:40.038246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b654faf5af09'
down_revision = 'eae6992b4b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
